theme: jekyll-theme-cayman

# Setup
title:        Artscape
tagline:      Support local artists. Enjoy beatiful 4K images. No licensing hassles.
baseurl:      "/Artscape"
locale:       "en"

# About/contact
author:
  name: ZGuy
  url: http://www.zguy.com
