theme: jekyll-theme-cayman

# Setup
title:        Artscape
tagline:      Enjoy beautiful 4K images. No licensing hassles. Directly support artists.
baseurl:      ""
locale:       "en"

# About/contact
author:
  name: ZGuy
  url: http://www.zguy.com
