theme: jekyll-theme-cayman

# Setup
title:        Artscape
description:      Support local artists. Enjoy Beatiful 4K images. No Licensing Hassles
baseurl:      "/Artscape"
locale:       "en"

# About/contact
author:
  name: ZGuy
  url: http://www.zguy.com
